---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: install Elasticsearch
  package:
    name: elasticsearch
    state: "{{ es_package_state }}"

- include_tasks: setup_security_ssl_transport.yml
  when: es_security_enable_ssl_transport

- name: configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: "{{ es_path_config }}/elasticsearch.yml"
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch

- name: configure JVM min heap size
  lineinfile:
    path: "{{ es_path_config }}/jvm.options"
    regexp: '^-Xms'
    line: -Xms{{ es_heap_size_min }}

- name: configure JVM max heap size
  lineinfile:
    path: "{{ es_path_config }}/jvm.options"
    regexp: '^-Xmx'
    line: -Xmx{{ es_heap_size_max }}

- name: force a restart if configuration has changed
  meta: flush_handlers

- name: start Elasticsearch.
  service:
    name: elasticsearch
    state: "{{ es_service_state }}"
    enabled: "{{ es_service_enabled }}"

- name: make sure Elasticsearch is running before proceeding
  wait_for:
    host: "{{ es_network_host }}"
    port: "{{ es_http_port }}"
    delay: 3
    timeout: 300
