---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: es01
    hostname: es01
    image: centos:7
    networks:
      - name: es-network
    exposed_ports:
      - 9200
      - 9300
    published_ports:
      - 0.0.0.0:9201:9200
    groups:
      - elasticsearch
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    tty: True
    environment:
      container: docker
  - name: es02
    hostname: es02
    image: centos:7
    networks:
      - name: es-network
    exposed_ports:
      - 9200
      - 9300
    published_ports:
      - 0.0.0.0:9202:9200
    groups:
      - elasticsearch
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    tty: True
    environment:
      container: docker
  - name: es03
    hostname: es03
    image: centos:7
    networks:
      - name: es-network
    exposed_ports:
      - 9200
      - 9300
    published_ports:
      - 0.0.0.0:9203:9200
    groups:
      - elasticsearch
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    tty: True
    environment:
      container: docker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
