---
- name: Converge
  hosts: all
  become: True
  tasks:
    - include_role:
        name: elasticsearch
      vars:
        es_network_host: 0.0.0.0
        es_network_publish_host: "{{ ansible_default_ipv4.address }}"
        #es_single_node: true
        es_discovery_seed_hosts: "{{ groups['elasticsearch'] | map('extract', hostvars, ['ansible_default_ipv4','address']) | list }}" 
        es_cluster_initial_master_nodes: "{{ groups['elasticsearch'] | map('extract', hostvars, ['ansible_default_ipv4','address']) | list }}"
        #es_discovery_seed_hosts: "{{ groups['elasticsearch'] | map('extract', hostvars, ['ansible_eth1','ipv4','address']) | list }}" 
        #es_cluster_initial_master_nodes: "{{ groups['elasticsearch'] | map('extract', hostvars, ['ansible_eth1','ipv4','address']) | list }}"
        #es_security_enable_xpack: true
        #es_security_enable_ssl_transport: true

